"""The news/pattern knowledge graph (§7, §17 Phase 6): the schema and an
in-memory engine standing in for FalkorDB (no Docker daemon in this
sandbox — see `store.py`'s doc comment). Ingest pipelines, outcome
resolution, the §7.2 queries, and fusion wiring are the rest of Phase 6,
built on top of this module.
"""

from .backfill import build_backfilled_graph
from .ingest import (
    attach_news_outcome,
    attach_pattern_outcome,
    ingest_market_regime,
    ingest_news_event,
    ingest_pattern_instance,
    ingest_trade,
    link_co_occurring_patterns,
)
from .outcomes import (
    FixedHorizonMove,
    OutcomeResolution,
    Verdict,
    resolve_fixed_horizon_move,
    resolve_pattern_outcome,
)
from .priors import FusionPriorInput, graph_prior_to_fusion_input
from .queries import (
    ConditionalReliability,
    ConfluenceResult,
    NewsImpactPeriod,
    conditional_reliability,
    confluence_discovery,
    news_impact_persistence,
)
from .schema import (
    Edge,
    EdgeLabel,
    Node,
    NodeLabel,
    co_occurred_with_edge,
    concept_node,
    correlated_with_edge,
    during_edge,
    event_type_node,
    expresses_edge,
    instance_of_edge,
    instrument_node,
    market_regime_node,
    mentions_edge,
    news_event_node,
    of_type_edge,
    on_edge,
    outcome_node,
    pattern_inst_node,
    pattern_node,
    preceded_edge,
    resolved_as_edge,
    session_node,
    trade_node,
    triggered_by_edge,
)
from .store import KnowledgeGraph

__all__ = [
    "Edge",
    "EdgeLabel",
    "Node",
    "NodeLabel",
    "KnowledgeGraph",
    "build_backfilled_graph",
    "FixedHorizonMove",
    "OutcomeResolution",
    "Verdict",
    "resolve_fixed_horizon_move",
    "resolve_pattern_outcome",
    "FusionPriorInput",
    "graph_prior_to_fusion_input",
    "ConditionalReliability",
    "ConfluenceResult",
    "NewsImpactPeriod",
    "confluence_discovery",
    "conditional_reliability",
    "news_impact_persistence",
    "attach_news_outcome",
    "attach_pattern_outcome",
    "ingest_market_regime",
    "ingest_news_event",
    "ingest_pattern_instance",
    "ingest_trade",
    "link_co_occurring_patterns",
    "co_occurred_with_edge",
    "concept_node",
    "correlated_with_edge",
    "during_edge",
    "event_type_node",
    "expresses_edge",
    "instance_of_edge",
    "instrument_node",
    "market_regime_node",
    "mentions_edge",
    "news_event_node",
    "of_type_edge",
    "on_edge",
    "outcome_node",
    "pattern_inst_node",
    "pattern_node",
    "preceded_edge",
    "resolved_as_edge",
    "session_node",
    "trade_node",
    "triggered_by_edge",
]
