//! ONNX inference for the strategy VM's model tier (§3.2: "Sub-millisecond
//! inference in-process, no Python in the loop"). §17 Phase 3's own exit
//! criterion is a parity test asserting this matches the Python-trained
//! model within 1e-6 — see `tests/onnx_parity.rs` for that test and
//! `crates/strategy/testdata/onnx_parity/` for the fixture it checks
//! against (generated by
//! `services/agents/packages/models/scripts/generate_onnx_fixture.py`,
//! committed rather than regenerated at Rust test time since this
//! environment's Rust tests have no Python to call).

use std::path::Path;

use ort::value::{DynMapValueType, Tensor};

#[derive(Debug, thiserror::Error)]
pub enum OnnxError {
    #[error("ort error: {0}")]
    Ort(#[from] ort::Error),
    #[error("model output did not contain a 'probabilities' entry")]
    MissingProbabilitiesOutput,
    #[error("model produced no rows in its probabilities output")]
    EmptyProbabilitiesOutput,
    #[error("class 1 not present in the model's probability map")]
    MissingPositiveClass,
    #[error("expected a {expected}-feature input row, got {actual}")]
    FeatureLengthMismatch { expected: usize, actual: usize },
}

/// Loads a binary LightGBM->ONNX classifier (as `onnxmltools.convert_lightgbm`
/// produces, via a scikit-learn-style `ZipMap` probabilities output) and
/// exposes single-row P(class=1) inference — the exact shape
/// `crates/risk::sizing`'s `KellyInputs.probability` needs.
pub struct OnnxClassifier {
    session: ort::session::Session,
    n_features: usize,
}

/// §17 Phase 9 "GPU inference," behind the `gpu` feature (off by default —
/// see this crate's Cargo.toml for why). CUDA is registered first with CPU
/// as an explicit fallback; `ort`'s own `apply_execution_providers` already
/// falls back to the next provider in the list (logging a warning) if an
/// earlier one fails to initialize, so this ordering is a real, exercised
/// degradation path even with no GPU present — this sandbox has neither
/// the hardware nor a CUDA runtime to accelerate anything with, so it
/// always and honestly takes the fallback branch; there is no way to
/// benchmark a speedup here, only to verify the path compiles, registers,
/// and still produces correct output (see `onnx_parity`'s `--features gpu`
/// run in CI/locally).
#[cfg(feature = "gpu")]
fn execution_providers() -> Vec<ort::ep::ExecutionProviderDispatch> {
    vec![ort::ep::CUDA::default().build(), ort::ep::CPU::default().build()]
}

#[cfg(not(feature = "gpu"))]
fn execution_providers() -> Vec<ort::ep::ExecutionProviderDispatch> {
    Vec::new()
}

impl OnnxClassifier {
    pub fn load(path: impl AsRef<Path>, n_features: usize) -> Result<Self, OnnxError> {
        // `with_execution_providers` returns `Error<SessionBuilder>` (it
        // hands the builder back on failure so a caller could retry with a
        // different provider list) rather than the plain `ort::Error` every
        // other fallible builder step here returns — an explicit `map_err`
        // bridges the two since `?` only performs one `From` hop.
        let mut builder = ort::session::Session::builder()?
            .with_execution_providers(execution_providers())
            .map_err(ort::Error::from)?;
        let session = builder.commit_from_file(path)?;
        Ok(Self { session, n_features })
    }

    /// The model's own **raw**, uncalibrated P(class=1) for one row of
    /// `n_features` values (§8.3: raw GBDT output is never itself the value
    /// that reaches `Signal.probability` — only after isotonic calibration,
    /// which is Phase 5 scope on the agent side once a real model exists).
    pub fn predict_positive_class_probability(&mut self, features: &[f32]) -> Result<f32, OnnxError> {
        if features.len() != self.n_features {
            return Err(OnnxError::FeatureLengthMismatch { expected: self.n_features, actual: features.len() });
        }
        let shape = [1i64, self.n_features as i64];
        let tensor = Tensor::from_array((shape, features.to_vec()))?;
        let outputs = self.session.run(ort::inputs!["input" => tensor])?;
        let probabilities = outputs.get("probabilities").ok_or(OnnxError::MissingProbabilitiesOutput)?;
        let rows = probabilities.try_extract_sequence::<DynMapValueType>()?;
        let first_row = rows.first().ok_or(OnnxError::EmptyProbabilitiesOutput)?;
        let class_probabilities = first_row.try_extract_map::<i64, f32>()?;
        class_probabilities.get(&1).copied().ok_or(OnnxError::MissingPositiveClass)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_a_feature_vector_of_the_wrong_length() {
        let fixture_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/testdata/onnx_parity");
        let model_path = format!("{fixture_dir}/model.onnx");
        if !Path::new(&model_path).exists() {
            eprintln!("skipping: fixture not present at {model_path}");
            return;
        }
        let mut classifier = OnnxClassifier::load(&model_path, 6).unwrap();
        let err = classifier.predict_positive_class_probability(&[1.0, 2.0]).unwrap_err();
        assert!(matches!(err, OnnxError::FeatureLengthMismatch { expected: 6, actual: 2 }));
    }
}
